### PR TITLE
[MAINT] add github action worflow for tests

### PR DESCRIPTION
**Pull request by Remi-Gau**
- test on all OS
- test on all python versions that are not at end of life
- drop travis
- add dependabot to keep GHA up to date (should ensure that tests are also run 'once in a while')

### CODE REVIEW

**Comment by cmaumet** [comment]
Thanks @Remi-Gau! Am I right that we should merge this and then trigger a PR so that the tests can be run and we find out whether they pass?

**Comment by Remi-Gau** [comment]
Previous runs were not that red: https://github.com/Remi-Gau/nidmresults/actions/runs/6230115666/job/16909666544

Unsure why the latest fails across the board: https://github.com/Remi-Gau/nidmresults/actions/runs/6237515552

**Comment by cmaumet** [comment]
Phew! 

The all red looks like an SSL certificate issue "certificate verify failed: certificate has expired (_ssl.c:1131)" 🤷‍♀️

**Comment by Remi-Gau** [comment]
yeah but that was not there on the previous run... some API not being happy about being pinged too much?

**Comment by Remi-Gau** [comment]
OK so just re running the failing workflows makes them pass eventually

so they look like flaky tests

so I would say merge and then make them less flaky

**Comment by cmaumet** [comment]
Sounds good to me! Thanks for investigating!

**Pull request merged**
