### PR TITLE
Peaks and Statistic maps reader

### PR DESCRIPTION
**Pull request by cmaumet**
This PR is work-in-progress to provide reading of NIDM-Results documents and export a list of peaks as a data frame. 

@vsoch: here is some preliminary work I did following the comments you provided at the Chicago meeting. This first function export the peaks as a data frame. More columns could be added depending on the application and this could also be extended to other objects in the model (contrasts...). 

Before going further, I just wanted to check if this can be of interest for your application...

### CODE REVIEW

**Comment by vsoch** [comment]
This would be useful, but it would be best to have as a query in nidm-query - it's getting confusing having in both places. Is this the same as the PR you did to nidm-query?

**Comment by cmaumet** [comment]
This is a variant of the PR I did to nidm-query and is also based on our [original peak query](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/query/peak.rq).

**Comment by cmaumet** [comment]
Part of this was written on my way back from Chicago. But, before going further, I would like to be sure this does not duplicate your work on nidm-query...

**Comment by cmaumet** [comment]
As discussed in #16, this PR creates peak and statistic map objects from a NIDM-Results document. An example of usage can be found in the [nidmreader script](https://github.com/cmaumet/nidmresults/blob/649b4fde2e88e6685d5dc125ccf40e01827b4bde/bin/nidmreader.py).

**Comment by cmaumet** [comment]
I am going to merge this one so that PR in progress (update to NIDM-Results 1.2.0) can include it.

**Pull request merged**
