### PR TITLE
add codespell: config, workflow and have typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@yarikoptic 
have you set some sort of global "just_run_add_codespell" to all repos

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
Actually can you add a precommit for codespell as well?

**Comment by yarikoptic** [comment]
indeed!  the crude script (https://github.com/yarikoptic/improveit/blob/main/codespellit) would have added it if there was a pre-commit in this repo... but it saw no config

**Comment by Remi-Gau** [comment]
OK will take care of the precommit thing in another PR

**Pull request merged**
